image: elementary/docker:stable

before_script:
    - valac --version
    - uname -a
    - apt-get update -qq && apt-get install -y -qq devscripts build-essential lintian

build:
    stage: build
    script:
        - debuild --no-tgz-check
        - cd debian
        - dpkg-deb --build com.gitlab.dusan-gvozdenovic.strings